# ActivityRoles, (c) Shadow 2022

# This plugin manages syncing between a player's Minecraft playtime and their Discord roles.
# There are two types of syncs:
#   Giving a player a role based on how long they have ever played on the server. (type: "total")
#   Giving a player a role based on how recently they have played on the server. (type: "seen")
#
# You can list times in either minutes, hours, days, or weeks, by using "m", "h", "d", or "w"
#
# NOTE: Offline players will only have their "seen" roles synced, they must be online to have their "total" role synced. This is a MC limitation.

roles:
  "new-player":
    id: "00000000000000000"
    duration: "5m"
    type: "total"
  "tier-one":
    id: "00000000000000000"
    duration: "2h"
    type: "total"
  "tier-two":
    id: "00000000000000000"
    duration: "6h"
    type: "total"
  "active":
    id: "00000000000000000"
    duration: "2w"
    type: "seen"
  "very-active":
    id: "00000000000000000"
    duration: "3d"
    type: "seen"


# If true, roles will only be updated when a player uses the /activity command
autosync-enabled: true
# How long should the autosync happen in seconds? Default: 1 minute
autosync-interval: 60

# Debug mode
debug: false
# DO NOT MANUALLY CHANGE THIS
config-version: 2